require_relative 'calculation/input_output'
require_relative 'calculation/calculator'
require_relative 'calculation/parser'
require_relative 'calculation/router'
require_relative 'calculation/operation'
require_relative'calculation/operations_history'